version: '2'
services:
    db: 
        image: mysql/mysql-server:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - db:/var/run/mysqld
        command: --default-authentication-plugin=mysql_native_password

    app: 
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db

volumes:
  db: